function [ text ] = getGroupsInformation( obj )
% GETGROUPSINFORMATION Display information about Groups.
%
% Syntax:
%   GETGROUPSINFORMATION( obj );
%
% Input parameters:
%   * data - data from json file(s)
%
% Example:
%   GETGROUPSINFORMATION( );
%
% Available at: https://github.com/NCN-Lab/DBScope
% For referencing, please use: Andreia M. Oliveira, Eduardo Carvalho, Beatriz Barros, Carolina Soares, Manuel Ferreira-Pinto, Rui Vaz, Paulo Aguiar, DBScope: 
% a versatile computational toolbox for the visualization and analysis of sensing data from Deep Brain Stimulation, doi: https://doi.org/10.1101/2023.07.23.23292136.
%
% Andreia M. Oliveira, Eduardo Carvalho, Beatriz Barros & Paulo Aguiar - NCN
% INEB/i3S 2022
% pauloaguiar@i3s.up.pt
% -----------------------------------------------------------------------

indx_sensing_initial = cellfun(@(c) isstruct(c) && numel(c.hemispheres) == 2, {obj.parameters.groups.initial(:).sensing});
indx_sensing_final = cellfun(@(c) isstruct(c) && numel(c.hemispheres) == 2, {obj.parameters.groups.final(:).sensing});

text = [ newline, 'Initial Channel Left: ', obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).channel, newline...
    '  ', newline...
    'Initial Location Left: ', obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).location, newline...
    '  ', newline...
    'Initial Rate Left: ',  num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).frequency), newline...
    '  ', newline...
    'Initial Pulse Width [MicroSecond] Left: ', num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).pulse_width), newline...
    '  ', newline...
    'Initial Center Frequency [Hz] Left: ',  num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).center_frequency), newline...
    '  ', newline...
    'Initial Channel Right: ', obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(1).channel, newline...
    '  ', newline...
    'Initial Location Right: ', obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(2).location, newline...
    '  ', newline...
    'Initial Rate Right: ', num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(2).frequency), newline...
    '  ', newline...
    'Initial Pulse Width [MicroSecond] Right: ', num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(2).pulse_width), newline...
    '  ', newline...
    'Initial Frequency [Hz] Right: ', num2str(obj.parameters.groups.(lower("Initial"))(indx_sensing_initial).sensing.hemispheres(2).center_frequency), newline...
    '  ', newline...
    'Initial Channel Left: ', obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).channel, newline...
    '  ', newline...
    'Final Location Left: ', obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).location, newline...
    '  ', newline...
    'Final Rate Left: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).frequency), newline...
    '  ', newline...
    'Final Pulse Width [MicroSecond] Left: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).pulse_width), newline...
    '  ', newline...
    'Final Frequency [Hz] Left: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).center_frequency), newline...
    '  ', newline...
    'Final Channel Right: ', obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(1).channel, newline...
    '  ', newline...
    'Final Location Right: ', obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(2).location, newline...
    '  ', newline...
    'Final Rate Left: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(2).frequency), newline...
    '  ', newline...
    'Final Pulse Width [MicroSecond] Right: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(2).pulse_width), newline...
    '  ', newline...
    'Final Frequency [Hz] Right: ', num2str(obj.parameters.groups.(lower("Final"))(indx_sensing_final).sensing.hemispheres(2).center_frequency) ];

disp(text);

end

